import type { Metadata } from 'next';
import './globals.css';
import { LayoutProvider } from '@/context/LayoutContext';
import { StyledEngineProvider, ThemeProvider as ThemeProviderV5 } from '@mui/material/styles';
import dark from '@/themes/dark';
import NavigationSidebar from '@/navigation/Sidebar/NavigationSidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <LayoutProvider>
          <StyledEngineProvider injectFirst>
            <ThemeProviderV5 theme={dark}>
              <NavigationSidebar />
              <main>{children}</main>
            </ThemeProviderV5>
          </StyledEngineProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
