import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { LayoutStateContext } from '../../web-ui-template/src/context/LayoutContext';
import { LayoutProvider } from '@/context/LayoutContext';
import { ThemeProvider as ThemeProviderV5 } from '@mui/material/styles';
import { StyledEngineProvider } from '@mui/material/styles';
import dark from '@/themes/dark';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <LayoutProvider>
          <StyledEngineProvider injectFirst>
            <ThemeProviderV5 theme={dark}>{children}</ThemeProviderV5>
          </StyledEngineProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}
